version: '3.8'

services:
  spark:
    image: deltaio/delta-docker:latest
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'  
      - '7077:7077'  
      - '4040:4040'  
    volumes:
      - ./data:/opt/spark-apps/data
      - ./app:/opt/spark-apps/app
      - ./output:/opt/spark-apps/output
      - ./config:/opt/spark/conf
    depends_on:
      - minio

  spark-worker:
    image: deltaio/delta-docker:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./data:/opt/spark-apps/data
      - ./app:/opt/spark-apps/app
      - ./output:/opt/spark-apps/output

  minio:
    image: quay.io/minio/minio
    command: ["server", "/data", "--console-address", ":9090"]
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000  
      - 9090:9090  

volumes:
  minio-data:
    driver: local